### ISSUE TITLE
Support HA for shards

### ISSUE THREAD

**Issue by jet-go** [tkestack/kvass#100]
Hello
Currently i'm trying to setup shards with high availability ie running the multiple replicas of each shard. I'm not sure whether this is already possible. Could you please let me know whether this can be achieved or not?
I did try to deploy 2 statefulsets with same config/coordinator, but the targets distribution was not the same in both sts pods.
If it's not supported, would love to help with the implementation (with some guidance to start with).

Example:
Let's assume for 2 sts with 2 shards -
I would expect each shard/pods (prom-replica-0-0 & prom-replica-0-1) to scrape the same targets & so on for other shards.

```yml
sts: prom-replica-0
pod: prom-replica-0-$(SHARD)
----config----
global:
  external_labels:
    prometheus: prom-kvass-$(SHARD)
    prometheus_replica: $(POD_NAME)
....
```
```yml
sts: prom-replica-1
pod: prom-replica-1-$(SHARD)
----config----
global:
  external_labels:
    prometheus: prom-kvass-$(SHARD)
    prometheus_replica: $(POD_NAME)
....
```

Thanks,
Jet
