### ISSUE TITLE
prometheus-rep-0-0 OOMKilled

### ISSUE THREAD

**Issue by UrmsOne** [tkestack/kvass#13]
环境信息：

* k8s集群共118个节点

* 每个prom的max-series 为80w，共6个prom

* 资源为8G、2Cpu

我使用一个集群外部的prom通过federate接口，抓取prometheus-rep-0-(0-5)pod中prom的数据时，发生OOMKilled

```
xxx1@localhost:~$ kubectl get po
NAME                                        READY     STATUS      RESTARTS   AGE
kvass-coordinator-58f4b8df79-47svs          2/2       Running     0          2h
prom-lua-proxy-deployment-758d58f6c-rql9l   1/1       Running     0          7m
prometheus-node1-7474c8758c-wkqg7           2/2       Running     1          23d
prometheus-rep-0-0                          2/3       OOMKilled   5          2h
prometheus-rep-0-1                          3/3       Running     3          2h
prometheus-rep-0-2                          3/3       Running     4          2h
prometheus-rep-0-3                          3/3       Running     3          2h
prometheus-rep-0-4                          3/3       Running     2          2h
prometheus-rep-0-5                          3/3       Running     1          2h
tensorflow-serving-58997667b8-6kkrv         1/1       Running     0          146d
thanos-query-6b69d8c69d-6hln6               1/1       Running     0          1d
```

config.yaml配置
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus-config
  namespace: xxx-dev
data:
  prometheus.yml: |-
    global:
      scrape_interval: 45s
      scrape_timeout: 45s
      evaluation_interval: 45s
      external_labels:
        server: 'k8s-monitor'
    scrape_configs:
    - job_name: 'kubernetes-u-nodes'
      kubernetes_sd_configs:
      - role: node
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
```
coordinator.yaml
```
apiVersion: v1
kind: Service
metadata:
  name: kvass-coordinator
  labels:
    app.kubernetes.io/name: kvass-coordinator
spec:
  ports:
    - name: http
      port: 9090
      targetPort: http
  selector:
    app.kubernetes.io/name: kvass-coordinator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: kvass-coordinator
  name: kvass-coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kvass-coordinator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kvass-coordinator
    spec:
      #serviceAccountName: prometheus
      serviceAccountName: xxx-dev-user
      containers:
        - name: config-reload
          args:
            - --reload-url=http://localhost:9090/-/reload
            - --config-file=/etc/prometheus/config/prometheus.yml
            - --config-envsubst-file=/etc/prometheus/config_out/prometheus.env.yaml
          image: rancher/coreos-prometheus-config-reloader:v0.32.0
          imagePullPolicy: Always
          resources:
            limits:
              memory: 240Mi
            requests:
              memory: 120Mi
          volumeMounts:
            - mountPath: /etc/prometheus/config_out
              name: config-out
            - mountPath: /etc/prometheus/config
              name: config
        #- image: tkestack/kvass:v0.0.3
        - image: kvass/urmsone-kvass
          imagePullPolicy: Always
          #imagePullPolicy: Never
          args:
            - coordinator
            - --shard.max-series=1000000
            - --shard.selector=app.kubernetes.io/name=prometheus
            - --shard.namespace=$(NAMESPACE)
            - --config.file=/etc/prometheus/config_out/prometheus.env.yaml
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 9090
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/prometheus/config
              name: config
            - mountPath: /etc/prometheus/config_out
              name: config-out
          name: kvass
          resources:
            limits:
              cpu: 4
              memory: 4Gi
            requests:
              cpu: 4
              memory: 2Gi
      volumes:
        - name: config
          configMap:
            name: prometheus-config
            defaultMode: 420
        - emptyDir: {}
          name: config-out
        - emptyDir: {}
          name: tls-assets
```
prometheus-rep-0.yaml
```
kind: Service
apiVersion: v1
metadata:
  name: prometheus
  namespace: xxx-dev
  labels:
    app.kubernetes.io/name: prometheus
spec:
  type: ClusterIP
  clusterIP: None
  selector:
   app.kubernetes.io/name: prometheus
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: web
    - name: grpc
      port: 10901
      targetPort: grpc
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: prometheus
  name: prometheus-rep-0
  namespace: xxx-dev
spec:
  # must set as Parallel
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
      kvass/rep: "0"
  serviceName: prometheus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus
        kvass/rep: "0"
    spec:
      containers:
        - name: thanos
          image: thanosio/thanos:v0.16.0-rc.1
          args:
            - sidecar
            - --tsdb.path=/prometheus
            - --prometheus.url=http://localhost:8080
            - --reloader.config-file=/etc/prometheus/config/prometheus.yml
            - --reloader.config-envsubst-file=/etc/prometheus/config_out/prometheus.env.yaml
          ports:
            - name: http-sidecar
              containerPort: 10902
            - name: grpc
              containerPort: 10901
          livenessProbe:
            httpGet:
              port: 10902
              path: /-/healthy
          readinessProbe:
            httpGet:
              port: 10902
              path: /-/ready
          volumeMounts:
            - mountPath: /etc/prometheus/config_out
              name: config-out
            - mountPath: /etc/prometheus/config
              name: config
        - name: kvass
          args:
            - sidecar
          image: kvass/urmsone-kvass
          imagePullPolicy: Always
          resources:
            limits:
              memory: 4Gi
              cpu: 4
            requests:
              memory: 2Gi
              cpu: 2
          volumeMounts:
            - mountPath: /etc/prometheus/config_out
              name: config-out
          ports:
            - containerPort: 8080
              name: web
              protocol: TCP

        - name: prometheus
          args:
            - --storage.tsdb.path=/prometheus
            - --storage.tsdb.retention.time=3h
            - --web.enable-lifecycle
            - --storage.tsdb.no-lockfile
            - --storage.tsdb.max-block-duration=2h
            - --storage.tsdb.min-block-duration=2h
            - --config.file=/etc/prometheus/config_out/prometheus_injected.yaml
          image: prom/prometheus:v2.19.2
          resources:
            limits:
              memory: 8Gi
              cpu: 2
            requests:
              memory: 8Gi
              cpu: 2
          ports:
            - containerPort: 9090
              name: web
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/prometheus/config
              name: config
            - mountPath: /etc/prometheus/config_out
              name: config-out
            - mountPath: /prometheus
              name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: xxx-dev-user
      securityContext:
        runAsUser: 0
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: prometheus-config
            defaultMode: 420
        - emptyDir: {}
          name: config-out
        - emptyDir: {}
          name: tls-assets
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
```
