### ISSUE TITLE
Documentation and Questions

### ISSUE THREAD

**Issue by Jakob3xD** [tkestack/kvass#18]
Hello,
this project sounds really interesting and I would like to use it.
Unfortunately you haven't wrote any documentation, which makes it hard for me to understand the full capability of your software.
Therefore I want to ask you some questions if it is possible or not.

I have two types of targets I want to scrape. One type needs a replica set with a and b and the other one only needs to be scraped by a singe Prometheus. Is kvass capable of creating a replica set of Proms with external_labels set in the Prometheus config, so that Thanos can us the label for de-duplication? I also want to add an external_label to each Prometheus which automatically increases. I should also mention that my targets are not inside any k8s cluster and are written in a static config.
For example:
```
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      external_labels:
        cluster: some-cluster
        prom_replica: a
        prom: prom-node-n

data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      external_labels:
        cluster: some-cluster
        prom_replica: b
        prom: prom-node-n
```
`prom-node-n` where n stands for a number which would count up for each replica set.
Is this possible with kvass?
