### ISSUE TITLE
修改metric_relabel_config配置后sidecar感知不到

### ISSUE THREAD

**Issue by like-inspur** [tkestack/kvass#33]
我修改了prometheus配置中某个job的metric_relabel_configs，指标过滤在原有process和go基础上添加http开头的，coordinator感知到了，sidecar感知不到，sidecar的启动参数配置如下：
```
/kvass sidecar --config.file=/etc/prometheus/config/prometheus.yml --config.output-file=/etc/prometheus/config_out/prometheus.yml
```

查看sidecar的--config.file和--config.output-file，发现sidecar没有感知配置file的修改从而去重载output-file

/etc/prometheus/config/prometheus.yml
```
- job_name: 'kubernetes-nodes'
  kubernetes_sd_configs:
  - role: node
  scrape_interval: 1m
  scrape_timeout: 1m
  relabel_configs:
  - source_labels: [__address__]
    regex: '(.*):10250'
    replacement: '${1}:10255'
    target_label: __address__
  - source_labels: [__meta_kubernetes_node_name]
    action: replace
    target_label: host
  - source_labels: [__address__]
    action: replace
    target_label: instance
  metric_relabel_configs:
  - source_labels: [__name__]
    regex: '(process|go|http)_.+'
    action: drop
```

/etc/prometheus/config_out/prometheus.yml 
```
- job_name: kubernetes-nodes
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 1m
  metrics_path: /metrics
  scheme: http
  proxy_url: http://127.0.0.1:8008
  relabel_configs:
  - separator: ;
    regex: __invalid_label_(.+)
    replacement: $1
    action: labelmap
  metric_relabel_configs:
  - source_labels: [__name__]
    separator: ;
    regex: (process|go)_.+  ——缺少修改的http
    replacement: $1
    action: drop
```
