### ISSUE TITLE
prometheus配置采用file_sd_configs作target发现时报错找不到文件

### ISSUE THREAD

**Issue by Felix-YuJing** [tkestack/kvass#58]
prometheus采用了类似如下的配置：
```
      - job_name: "node"
        file_sd_configs:
          - refresh_interval: 1m
            files:
              - "/etc/prometheus/config_pvc/node/*.yml"
```
`/etc/prometheus/config_pvc/node/`下会动态更新需要监控的target文件，但发现coordinator日志有如下报错，实际上文件确实存在的：
```
level=error ts=2021-06-04T03:18:06.090Z caller=file.go:344 component="discovery manager scrape" discovery=file msg="Error reading file" path=/etc/prometheus/config_pvc/node/xxxxxxxxxxxxxxx.yml err="open /etc/prometheus/config_pvc/node/xxxxxxxxxxxxxxxyml: no such file or directory"
```
